# Default values for slurm-sre-auth-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scarbo/slurm-sre-auth-service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 2121
  external_port: 2121

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
